"use client";

import { useEffect, useState } from "react";
import { getManagerStats } from "@/actions/manager-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Printer, Wallet, Users } from "lucide-react";
import { Loader2 } from "lucide-react";

export default function SummaryPage() {
  const [stats, setStats] = useState<{
    cashCollected: number;
    totalPasses: number;
  } | null>(null);

  useEffect(() => {
    getManagerStats().then(setStats);
  }, []);

  if (!stats) {
    return (
      <div className="flex items-center justify-center h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="p-6 max-w-md mx-auto space-y-6">
      <div className="flex items-center justify-between print:hidden">
        <h1 className="text-2xl font-bold">Daily Summary</h1>
        <Button onClick={() => window.print()} variant="outline">
          <Download className="mr-2 h-4 w-4" />
          Save PDF
        </Button>
      </div>

      <div className="print:p-8 print:border print:border-black print:rounded-none space-y-8">
        <div className="text-center space-y-2">
          <h2 className="text-3xl font-bold">SENTINEL</h2>
          <p className="text-muted-foreground">Manager Collection Report</p>
          <p className="text-sm text-muted-foreground">
            {new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}
          </p>
        </div>

        <div className="grid grid-cols-1 gap-4">
          <Card className="border-2 border-primary/10 shadow-none">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Wallet className="h-4 w-4" />
                Total Cash Collected
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">
                Rs. {stats.cashCollected.toLocaleString()}
              </div>
            </CardContent>
          </Card>

          <Card className="border-2 border-primary/10 shadow-none">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Users className="h-4 w-4" />
                Total Passes Issued
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">{stats.totalPasses}</div>
            </CardContent>
          </Card>
        </div>

        <div className="text-center text-xs text-muted-foreground pt-8 border-t">
          <p>Generated by Sentinel Access Control System</p>
          <p>Confidential Financial Document</p>
        </div>
      </div>
    </div>
  );
}
